### ISSUE TITLE
自行编译

### ISSUE THREAD

**Issue by wsycarlos** [Akegarasu/ok-derby#13]
你好，如若要自行编译，不知可否放出 main.spec 文件，谢谢！

**Comment by Akegarasu** [comment]
有绝对路径，不方便上传。
都能自己编译了为什么不直接运行呢

**Comment by wsycarlos** [comment]
哦 这样子
python不是熟悉的语言，想研究下pyinstaller是怎么编译的
运行自然是没什么问题
