### ISSUE TITLE
可能是BUG

### ISSUE THREAD

**Issue by ahuttyy** [Akegarasu/ok-derby#7]
作者大大你好，最近刚玩赛马娘，看到这个程序就直接开始使用了，不得不说设置好之后脚本比我还会养马，但是在使用过程中，我发现脚本在无法直接看结果的赛事上会直接卡住，不做任何操作，同时显示下面这行信息：
 INFO [auto_derby.template]: no match: tmpl=('single_mode_live_button.png', 'single_mode_race_next_button.png')
不清楚是我设置错误还是出现了bug，希望作者大大可以指点一下

**Comment by Akegarasu** [comment]
并不是bug，程序不会在你没跑过的比赛帮你点那个开始，只会在跑过的比赛上点跳过。
没跑过的比赛手动跑一下吧
